name: Build BIN
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile ESP32-C3 Sketch
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: esp32:esp32:esp32c3
          sketch-names: sketch.ino

      - name: Upload BIN
        uses: actions/upload-artifact@v4
        with:
          name: firmware-bin
          path: build/*.bin
